# Generated by Django 3.1.1 on 2020-11-15 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('emp_num', models.IntegerField(default=0)),
                ('adress', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=50, unique=True)),
                ('com_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_partner', to='crs_api.company', to_field='name')),
                ('com_1_employees', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_partner_employees', to='crs_api.company', to_field='name')),
                ('com_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_partner', to='crs_api.company', to_field='name')),
                ('com_2_employees', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_partner_employees', to='crs_api.company', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('position', models.CharField(choices=[('1', 'general manager'), ('2', 'manager'), ('3', 'department head'), ('4', 'employee')], default='-', max_length=50)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=models.SET('-'), related_name='employees', to='crs_api.company', to_field='name')),
            ],
        ),
    ]
